### ISSUE TITLE
Support utilisateur et mot de passe

### ISSUE THREAD

**Issue by jarobase** [kevincaradant/jarvis-kodi#3]
Pour plus de sécurités, il est possible de définir un nom d'utilisateur et un mot de passe pour prendre le contrôle de kodi. Il serait intéressant de pouvoir définir ces paramètres. Sans ça, le plugin ne sera pas utilisable dans de nombreux cas.

**Comment by kevincaradant** [comment]
Hello faut que je regarde comment faire cela :), je ne suis plus du tout sur le projet depuis longtemps malheureusement par manque de temps, si cela n'est pas trop compliqué je vais essayer d'y réfléchir ')

**Comment by kevincaradant** [comment]
@jarobase, feature en cours, j'essaie de finir cela rapidement car plus disponible pendant au moins une bonne semaine et cela d'ici 2 jours.
Désolé du retard, cela dit la modification n'est pas compliquée, j'espère que tu as pu te débrouiller sans mon aide en attendant :/

**Comment by kevincaradant** [comment]
@jarobase 

Désolé, j'ai eu qques occupations personnelles qui font que je n'ai jamais déployé la nouvelle version depuis 3 mois. De plus, j'ai eu un soucis avec la lib jq mais un collaborateur de Jarvis m'a bien aidé donc je devrais réussir à faire le truc.
Je suis en train de préparer une nouvelle release qui j'espère sera prête demain :)

**Comment by kevincaradant** [comment]
closed https://github.com/kevincaradant/jarvis-kodi/commit/9ad89c60a28cb875e648cbfc817064f96ea38668

Ouvre à nouveau ce ticket si nécessaire

**Comment by jarobase** [comment]
Super ! Merci pour le boulot accompli !
