### ISSUE TITLE
Multi Kodi

### ISSUE THREAD

**Issue by bricolgloo** [kevincaradant/jarvis-kodi#4]
Bonjour, 

je suis en train de découvrir votre plugin et j'ai lu votre échange de l'an dernier avec tzakarian , c'est genial ce que vous avez mis en place ! 
j'ai une question/demande, j'ai plusieurs kodi/osmc qui tournent chez moi, un jarvis et le tout bien intégré avec mon jeedom

j'aimerai pouvoir/savoir indiquer soit a jarvis ou au plug jarvis kodi,quels sont les "lieu(objet dans jeedom)" ou sont situés mes rpi avec un kodi pour pouvoir lancer des commandes comme : 

- controle kodi
- lance serie X saison X episode X dans "Chambre Enfants/Salon/etc"

est-ce quelquechose de possible ? 
Par avance merci pour votre retour !

**Comment by kevincaradant** [comment]
Hello

Oui cela me semble tout à fait possible. Il faut jouer avec une variable entre les fichiers commands, functions.sh et config.sh. Je n'ai pas entièrement réfléchie au truc mais  on peut  construire X variables dans config.sh et après dans functions.sh   on dit si variable = Salon alors on appel tel ip et tel port sinon si c'est égale à enfant alors on appel tel  ip et port sinon ça sera les valeurs par default. Bref ils faut avoir autant de paire de variable dans config.sh que d'instance de Kodi. J'essaierais ce week-end de m'y repencher un peu si je ne suis pas clair ')

**Comment by bricolgloo** [comment]
Coucou ,

Je suis pas codeur donc certains trucs me dépassent un peu mais dans l'esprit c'est ça oui ! 
Dans le config il faudrai pouvoir dupliquer le bloc qui existe actuellement et qu'on puisse leur affecter un pti nom propre , si je peux résumer avec mes mots !
Je trouve que ça renforce le côté multiroom de Jarvis ! (Il faut que je teste à l'occasion le Jarvis esclave aussi !)

Merci à toi en tous cas de te pencher sur ma demande :-) 

Dispo pour test quand tu sera prêt ;)
Bonne soirée

**Comment by kevincaradant** [comment]
OK, ça marche ! De rien et cool pour les tests car je pense que j'aurais du mal à tester de mon côté. Je te tiens au courant ! 

@bricolgloo, En cours de dev :), mais je bloque sur une certaine utilisation de la librairie jq. Dès que j'ai réussi a faire ce que je veux cela devrait aller vite ;)

**Comment by kevincaradant** [comment]
@bricolgloo 

Après avoir été en standby qques mois, j'ai repris aujourd'hui et je pense pouvoir sortir une nouvelle version demain. J'espère que tu pourras me dire si cela fonctionne correctement :)

**Comment by kevincaradant** [comment]
closed https://github.com/kevincaradant/jarvis-kodi/commit/9ad89c60a28cb875e648cbfc817064f96ea38668

Ouvre à nouveau ce ticket si nécessaire
